POST http://localhost:8000/api/v1/item/
Content-Type: application/json

{
  "code_items": 4,
  "name": "Hleb",
  "weight": 45,
  "code_factor": 3
}

###

POST http://localhost:8000/api/v1/order/
Content-Type: application/json

{
  "code_orders": 4,
  "number": 54,
  "summary": 3,
  "code_items": 4
}

###

POST http://localhost:8000/api/v1/orderer/
Content-Type: application/json

{
  "name": "AGM ENT"
}

###

POST http://localhost:8000/api/v1/factor/
Content-Type: application/json

{
  "num_factors": 4,
  "type_item": "Hlebushek",
  "sort_muka": "Pshenichnaya",
  "sum_of_worker": 50
}

###

POST http://localhost:8000/api/v1/production/
Content-Type: application/json

{
  "code_items": 4,
  "is_ready": "true"
}