# Generated by Django 4.1.13 on 2024-05-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_factors', models.IntegerField()),
                ('type_item', models.CharField(max_length=100)),
                ('sort_muka', models.CharField(max_length=100)),
                ('sum_of_workers', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Производственные цеха',
                'verbose_name_plural': 'Производственные цеха',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_items', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('code_factor', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Изделия',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.CreateModel(
            name='Orderers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Заказчики',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_orders', models.IntegerField()),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('summary', models.IntegerField()),
                ('code_items', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_items', models.IntegerField()),
                ('date', models.DateField()),
                ('is_ready', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Цеха',
                'verbose_name_plural': 'Цеха',
            },
        ),
    ]
